name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies (Yarn Classic)
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Type Check (Flow)
        run: yarn flow

      - name: Tests
        run: yarn test --ci

      - name: Build
        run: yarn build
